final-evaluate-pyramidal-mandarin: !LoadSerialized
   filename: /home/jialu/xnmt/recipes/las-tedlium/models/las-pyramidal-mandarin.mod
   overwrite:
   - path: train
     val: null
   - path: evaluate
     val:
       - !AccuracyEvalTask
          eval_metrics: wer,cer
          src_file: '{DATA_DIR}/dev.h5'
          ref_file: '{DATA_DIR}/dev.words'
          hyp_file: '{EXP_DIR}/logs/{EXP}.dev_hyp'
          inference: !AutoRegressiveInference
            batcher: !InOrderBatcher
              batch_size: 1
              pad_src_to_multiple: 8
              src_pad_token: ~
            max_src_len: 1500
            post_process: join-char
            search_strategy: !BeamSearch
              max_len: 500
              beam_size: 20
              len_norm: !PolynomialNormalization
                apply_during_search: true
                m: 1.5
       - !LossEvalTask
          max_src_len: 1500
          src_file: '{DATA_DIR}/dev.h5'
          ref_file: '{DATA_DIR}/dev.char'
          batcher: !InOrderBatcher
            batch_size: 1
            pad_src_to_multiple: 8
            src_pad_token: ~
