las-evaluate-multilingual: !LoadSerialized
  filename: /home/jialu/xnmt/recipes/las-tedlium/models/las-evaluate-multilingual.mod
  overwrite:
  # - path: evaluate.0.src_file
  #   val: '{CHI_DATA_DIR}/test_5.h5'
  # - path: evaluate.0.ref_file
  #   val: '{CHI_DATA_DIR}/test_5.words'
  - path: train.tasks.0.run_for_epochs
    val: 0
  - path: train.tasks.1.run_for_epochs
    val: 0
  - path: evaluate
    val:
      - !AccuracyEvalTask
        model: !Ref {default: 1928437192847, name: null, path: train.tasks.0.model}
        eval_metrics: wer,cer
        # src_file: '{ENG_DATA_DIR}/feat/test.h5'
        # ref_file: '{ENG_DATA_DIR}/transcript/test.words'
        src_file: '/home/jialu/TIMIT/test_5.h5'
        ref_file: '/home/jialu/TIMIT/test_5.words'
        hyp_file: '{EXP_DIR}/logs/{EXP}.eng_test_hyp'
        inference: !AutoRegressiveInference
          batcher: !InOrderBatcher
            batch_size: 1
            pad_src_to_multiple: 8
            src_pad_token: ~
          max_src_len: 1500
          post_process: join-char
          search_strategy: !BeamSearch
            max_len: 500
            beam_size: 20
            len_norm: !PolynomialNormalization
              apply_during_search: true
              m: 1.5
      - !LossEvalTask
        model: !Ref {default: 1928437192847, name: null, path: train.tasks.0.model}
        max_src_len: 1500
        # src_file: '{ENG_DATA_DIR}/feat/test.h5'
        # ref_file: '{ENG_DATA_DIR}/transcript/test.char'
        src_file: '/home/jialu/TIMIT/test_5.h5'
        ref_file: '/home/jialu/TIMIT/test_5.char'
        batcher: !InOrderBatcher
          batch_size: 1
          pad_src_to_multiple: 8
          src_pad_token: ~
      - !AccuracyEvalTask
        model: !Ref {default: 1928437192847, name: null, path: train.tasks.1.model}
        eval_metrics: wer,cer
        src_file: '{CHI_DATA_DIR}/test_5.h5'
        ref_file: '{CHI_DATA_DIR}/test_5.words'
        hyp_file: '{EXP_DIR}/logs/{EXP}.chi_test_hyp'
        inference: !AutoRegressiveInference
          batcher: !InOrderBatcher
            batch_size: 1
            pad_src_to_multiple: 8
            src_pad_token: ~
          max_src_len: 1500
          post_process: join-char
          search_strategy: !BeamSearch
            max_len: 500
            beam_size: 20
            len_norm: !PolynomialNormalization
              apply_during_search: true
              m: 1.5
      - !LossEvalTask
        model: !Ref {default: 1928437192847, name: null, path: train.tasks.1.model}
        max_src_len: 1500
        src_file: '{CHI_DATA_DIR}/test_5.h5'
        ref_file: '{CHI_DATA_DIR}/test_5.char'
        batcher: !InOrderBatcher
          batch_size: 1
          pad_src_to_multiple: 8
          src_pad_token: ~
