las-timit-evaluate-kmeans-100-clusters: !LoadSerialized
   filename: /home/jialu/xnmt/recipes/las-tedlium/models/las-timit-pretrain-test.mod
   overwrite:
   - path: train
     val: null
   - path: evaluate
     val:
       - !AccuracyEvalTask
          eval_metrics: wer,cer
          src_file: '{DATA_DIR}/test.h5'
          ref_file: '{DATA_DIR}/test.words'
          hyp_file: '{EXP_DIR}/logs/{EXP}.test_hyp'
          inference: !AutoRegressiveInference
            batcher: !InOrderBatcher
              batch_size: 1
              pad_src_to_multiple: 8
              src_pad_token: ~
            max_src_len: 1500
            post_process: join-char
            search_strategy: !BeamSearch
              max_len: 500
              beam_size: 20
              len_norm: !PolynomialNormalization
                apply_during_search: true
                m: 1.5
